/*
https://www.db4free.net
Você pode criar seu banco de dados neste site, caso não queira instalar o XAMPP!
*/
CREATE SCHEMA CLINICA_MEDICA;
USE CLINICA_MEDICA;


CREATE TABLE TIPO_SALA (
	COD_TIPO_SALA			INT 			NOT NULL 	AUTO_INCREMENT,
	DSC_TIPO_SALA			VARCHAR(100)	NOT NULL,
	IDF_ATIVO				VARCHAR(1)		DEFAULT 'S',
	PRIMARY KEY (COD_TIPO_SALA)
);

CREATE TABLE SALA (
	NUM_SALA				INT				NOT NULL 	AUTO_INCREMENT,
	DSC_SALA				VARCHAR(30)		NOT NULL,
	IDF_SITUACAO			VARCHAR(1)		DEFAULT 'D',
	COD_TIPO_SALA			INT				NOT NULL,
	PRIMARY KEY (NUM_SALA),
	FOREIGN KEY (COD_TIPO_SALA) REFERENCES TIPO_SALA (COD_TIPO_SALA)
);

CREATE TABLE DEPARTAMENTO (
	COD_DEPARTAMENTO 		INT 			NOT NULL 	AUTO_INCREMENT,
	NOM_DEPARTAMENTO 		VARCHAR(100) 	NOT NULL,
	IDF_ATIVO 				VARCHAR(01) 	NOT NULL,
	PRIMARY KEY (COD_DEPARTAMENTO)
);

CREATE TABLE ESPECIALIDADE (
	COD_ESPECIALIDADE 		INT 			NOT NULL 	AUTO_INCREMENT,
	DSC_ESPECIALIDADE 		VARCHAR(150) 	NOT NULL,
	PRIMARY KEY (COD_ESPECIALIDADE)
);

CREATE TABLE MEDICO (
	CRM_MEDICO 				INT 			NOT NULL,
	NOM_MEDICO 				VARCHAR(255) 	NOT NULL,
	COD_DEPARTAMENTO 		INT,
	PRIMARY KEY (CRM_MEDICO),
	FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO (COD_DEPARTAMENTO)
);

CREATE TABLE ESPECIALIDADE_MEDICO (
	CRM_MEDICO 				INT 			NOT NULL,
	COD_ESPECIALIDADE 		INT 			NOT NULL,
	PRIMARY KEY (COD_ESPECIALIDADE),
	FOREIGN KEY (CRM_MEDICO) 		REFERENCES MEDICO (CRM_MEDICO),
	FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE (COD_ESPECIALIDADE)
);

CREATE TABLE CAPITULO_CID (
	COD_CAPITULO_CID 		INT 			NOT NULL 	AUTO_INCREMENT,
	SGL_CAPITULO_CID 		VARCHAR(03) 	NOT NULL,
	DSC_CAPITULO_CID 		VARCHAR(100) 	NOT NULL,
	PRIMARY KEY (COD_CAPITULO_CID)
);

CREATE TABLE CID (
	COD_CID 				INT 			NOT NULL 	AUTO_INCREMENT,
	DSC_CID 				VARCHAR(100) 	NOT NULL,
	COD_CAPITULO_CID 		INT 			NOT NULL,
	PRIMARY KEY (COD_CID),
	FOREIGN KEY (COD_CAPITULO_CID) REFERENCES CAPITULO_CID (COD_CAPITULO_CID)
);

CREATE TABLE CIDADE (
	COD_CIDADE 				INT 			NOT NULL 	AUTO_INCREMENT,
	NOM_CIDADE 				VARCHAR(100) 	NOT NULL,
	SGL_ESTADO 				VARCHAR(02) 	NOT NULL,
	PRIMARY KEY (COD_CIDADE)
);

CREATE TABLE LABORATORIO (
	COD_LABORATORIO 		INT 			NOT NULL 	AUTO_INCREMENT,
	NOM_LABORATORIO 		VARCHAR(150) 	NOT NULL,
	COD_CIDADE 				INT 			NOT NULL,
	PRIMARY KEY (COD_LABORATORIO),
	FOREIGN KEY (COD_CIDADE) REFERENCES CIDADE (COD_CIDADE)
);

CREATE TABLE PACIENTE (
	COD_PACIENTE 			INT 			NOT NULL 	AUTO_INCREMENT,
	NOM_PACIENTE 			VARCHAR(150) 	NOT NULL,
	END_PACIENTE 			VARCHAR(150) 	NOT NULL,
	IDF_SEXO 				VARCHAR(1) 		NOT NULL,
	COD_CIDADE 				INT				NOT NULL,
	COD_CID 				INT 			NOT NULL,
	PRIMARY KEY (COD_PACIENTE),
	FOREIGN KEY (COD_CIDADE)	REFERENCES CIDADE (COD_CIDADE),
	FOREIGN KEY (COD_CID) 		REFERENCES CID (COD_CID)
);

CREATE TABLE TELEFONE_PACIENTE (
	COD_PACIENTE 			INT 			NOT NULL,
	NUM_TELEFONE_PACIENTE	VARCHAR(12) 	NOT NULL,
	PRIMARY KEY (NUM_TELEFONE_PACIENTE),
	FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTE (COD_PACIENTE)
);

CREATE TABLE CONSULTA (
	NUM_CONSULTA 			INT 			NOT NULL 	AUTO_INCREMENT,
	DATA_AGENDAMENTO 		DATETIME 		NOT NULL,
	DATA_ATENDIMENTO 		DATETIME 		NOT NULL,
	DSC_DIAGNOSTICO 		VARCHAR(255) 	NOT NULL,
	DSC_ANALISE_CLINICA 	VARCHAR(255),
	IDF_SITUACAO 			VARCHAR(1) 		NOT NULL,
	CRM_MEDICO 				INT				NOT NULL,
	COD_PACIENTE 			INT				NOT NULL,
	NUM_SALA				INT				NOT NULL,
	PRIMARY KEY (NUM_CONSULTA),
	FOREIGN KEY (CRM_MEDICO) 	REFERENCES MEDICO (CRM_MEDICO),
	FOREIGN KEY (COD_PACIENTE) 	REFERENCES PACIENTE (COD_PACIENTE),
	FOREIGN KEY (NUM_SALA) 		REFERENCES SALA (NUM_SALA)
);

CREATE TABLE MEDICAMENTO (
	COD_MEDICAMENTO 		INT 			NOT NULL 	AUTO_INCREMENT,
	NOM_MEDICAMENTO 		VARCHAR(150) 	NOT NULL,
	IDF_TIPO_MEDICAMENTO 	VARCHAR(1) 		NOT NULL,
	QTD_ESTOQUE 			INT 			DEFAULT 0,
	VLR_CUSTO_MEDICAMENTO	DECIMAL(10,2)	DEFAULT 0,
	COD_LABORATORIO 		INT 			NOT NULL,
	PRIMARY KEY (COD_MEDICAMENTO),
	FOREIGN KEY (COD_LABORATORIO) REFERENCES LABORATORIO (COD_LABORATORIO)
);

CREATE TABLE RECEITA (
	NUM_RECEITA  			INT 			NOT NULL 	AUTO_INCREMENT,
	DATA_RECEITA 			DATETIME 		NOT NULL,
	DSC_ORIENTACOES_GERAIS 	VARCHAR(150) 	NOT NULL,
	NUM_CONSULTA 			INT				NOT NULL,
	PRIMARY KEY (NUM_RECEITA),
	FOREIGN KEY (NUM_CONSULTA) REFERENCES CONSULTA (NUM_CONSULTA)
);

CREATE TABLE PRESCRICAO (
	NUM_RECEITA 			INT 			NOT NULL,
	COD_MEDICAMENTO 		INT 			NOT NULL,
	DSC_ORIENTACOES 		VARCHAR(150) 	NOT NULL,
	DSC_DOSAGEM 			VARCHAR(150),
	DSC_APRESENTACAO 		VARCHAR(150),
	IDF_RETIROU_MEDICAMENTO VARCHAR(1) 		DEFAULT 'N',
	PRIMARY KEY (NUM_RECEITA, COD_MEDICAMENTO),
	FOREIGN KEY (NUM_RECEITA) REFERENCES RECEITA (NUM_RECEITA),
	FOREIGN KEY (COD_MEDICAMENTO) REFERENCES MEDICAMENTO (COD_MEDICAMENTO)
);

CREATE TABLE PEDIDO_COMPRA (
	NUM_PEDIDO_COMPRA				INT				NOT NULL 	AUTO_INCREMENT,
	DTA_HOR_PEDIDO_COMPRA			DATETIME		NOT NULL,
	IDF_SITUACAO_PEDIDO_COMPRA		VARCHAR(1)		DEFAULT 'A',
	COD_LABORATORIO					INT				NOT NULL,
	PRIMARY KEY (NUM_PEDIDO_COMPRA),
	FOREIGN KEY (COD_LABORATORIO) REFERENCES LABORATORIO (COD_LABORATORIO)
);

CREATE TABLE MEDICAMENTO_PEDIDO_COMPRA (
	SEQ_MEDICAMENTO_PEDIDO_COMPRA	INT				NOT NULL 	AUTO_INCREMENT,
	NUM_PEDIDO_COMPRA				INT 			NOT NULL,
	COD_MEDICAMENTO					INT 			NOT NULL,
	QTD_MEDICAMENTO					INT				NOT NULL,
	VLR_PAGO_MEDICAMENTO			DECIMAL(10,2)	NOT NULL,
	PRIMARY KEY (SEQ_MEDICAMENTO_PEDIDO_COMPRA),
	FOREIGN KEY (NUM_PEDIDO_COMPRA) REFERENCES PEDIDO_COMPRA (NUM_PEDIDO_COMPRA)
);
